# Generated by Django 5.2.4 on 2025-07-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                default=1,
                help_text="Оплаченный урок",
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.lesson",
                verbose_name="Оплаченный урок",
            ),
            preserve_default=False,
        ),
    ]
