# Generated by Django 5.2.4 on 2025-07-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="owner",
        ),
    ]
