# Generated by Django 5.2.4 on 2025-08-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_owner_lesson_owner"),
        ("users", "0007_payment_is_paid_payment_stripe_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Оплаченный курс",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Оплаченный урок",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
