# Generated by Django 5.2.4 on 2025-08-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_paid_course_alter_payment_paid_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_payment_url",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_session_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счёт"), ("stripe", "Stripe")],
                help_text="Способ оплаты",
                max_length=30,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.CreateModel(
            name="PaymentStripe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                ("stripe_session_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stripe", to="users.payment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe-платёж",
                "verbose_name_plural": "Stripe-платежи",
            },
        ),
    ]
