# Generated by Django 5.2.4 on 2025-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_payment_is_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstripe",
            name="stripe_session_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
