# Generated by Django 5.2.4 on 2025-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_paymentstripe_stripe_session_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Статус подписки", verbose_name="Подписка на курс"),
        ),
    ]
