# Generated by Django 5.2.4 on 2025-08-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"], "verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["id"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
